version: '2.1'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - /tmp/sonarqube/data:/opt/sonarqube/data
      - /tmp/sonarqube/logs:/opt/sonarqube/logs
